# Generated by Django 5.0.6 on 2024-05-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0002_alter_contact_createdat_alter_contact_deletedat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ids',
        ),
    ]
