# Generated by Django 5.0.6 on 2024-05-23 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identify', '0003_remove_contact_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='deletedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
